# reference: http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode8
language: objective-c
rvm: 2.2.2

before_install:

- sudo gem install cocoapods -v '1.1.1'

- cd Example && rm -rf Pods && pod install && cd -
script:
- xcodebuild -workspace Example/URBNConvenience.xcworkspace -scheme URBNConvenience clean build -destination "platform=iOS Simulator,name=iPhone 6,OS=latest" -destination-timeout 120 test
